export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const SIGN_UP = "SIGN_UP";
export const SAVE_CONTACTS = "SAVE_CONTACTS";
export const UPDATEPROFILE = "UPDATEPROFILE";
export const SETTINGSUPDATE = "SETTINGSUPDATE";
export const BLOCKARRAY = "BLOCKARRAY";
